
version: "2"

services:

  chessai:
    image: chessai-train
    build:
      context: .
    entrypoint: ["python", "main.py"]
    volumes:
      - './model_weights:/app/models'
      - './logs:/app/logs'
    mem_limit: 500m
