
# use docker-compose 2
version: "2"

# define the containers to be started
services:

  # dummy container for building the base image
  chesslib-base:

    # auto-build the chesslib image
    build:
      context: ./ChessLib.Py
    # tag the image accordingly, so deriving images can build as well
    image: chesslib-python3

  # ai runtime container
  reinf-chess-ai:

    # signal that the chesslib-base container needs to execute first
    # this ensures that the base image is ready when building the Dockerfile
    depends_on:
      - chesslib-base  

    # automatically build the Dockerfile from the ChessLib.Py submodule
    build:
      context: .

    # start the reinf-chessai.py script on startup using the entrypoint
    command: reinf-chessai.py

    environment:
      MODEL_OUT: "/home/ai/model"

    volumes:
      - './model_out:/home/ai/model'
